version: '3'

services:
  web:
    image: igorproliveira/tech3:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://dpg-cl5t9pk72pts73etmiq0-a.oregon-postgres.render.com:5432/teste_khkw
      - POSTGRES_USERNAME=teste
      - POSTGRES_PASSWORD=YV5Xb7BXtEPgpa7q30eXIWdbQC66MHTO